version: '3.5'
services:
  httpbin:
    # this should basically match docker_reverse_proxy.tf
    image: kennethreitz/httpbin
    ports:
      - 8888:80
    networks:
      my_net:
networks:
  my_net:
    # name: my_net
