# This is a basic workflow to help you get started with Actions

name: Publish

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the first-skeleton branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo Hello, world!

    - name: Set up Emacs
      uses: purcell/setup-emacs@master
      with:
        version: 26.1

    - name: get htmlize
      run: wget https://raw.githubusercontent.com/hniksic/emacs-htmlize/master/htmlize.el

    - name: export
      run: emacs docker-toolbelt.org -Q -batch -l htmlize.el -f org-html-export-to-html
    # Runs a set of commands using the runners shell
    - name: rename
      run: mv docker-toolbelt.html index.html

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./
        allow_empty_commit: true
        # enable_jekyll: true
        # cname: github.peaceiris.com

    # - name: Deploy to GitHub Pages
    #   if: success()
    #   uses: crazy-max/ghaction-github-pages@v2
    #   with:
    #     target_branch: gh-pages
    #     build_dir: ./
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    # - name: Bye
    #   run: |
    #     echo DONE!
